// <auto-generated />
namespace Nautabus.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nb00001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nb00001));
        
        string IMigrationMetadata.Id
        {
            get { return "201507131223442_Nb0.0.001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
